### PR TITLE
Add sound when Pomodoro ends

### PR DESCRIPTION
**Pull request by gunar**
I've added a small .wav file from [Freesound.org](http://freesound.org/people/CJ4096/sounds/66717/), signaling the end of a pomodoro.

This requires `aplay`, but I guess most people have it.

Thank you for this awesome piece of software.

### CODE REVIEW

**Comment by gunar** [comment]
Typo fixed in this PR.

**Comment by optama** [comment]
Good idea, I have a similar line, actually also using aplay but I've put it in the callback function (finish_callback) in rc.lua. That way awmodoro makes no assumptions on users environment (aplay or not, choice of sound file etc) and it works satisfactory. 

Did you have any specific ideas in mind as to why it should be in the internals of awmodoro and not the provided callbacks?

**Comment by gunar** [comment]
Interesting point of view. I thought that by putting it in awmodoro's
internals others after me wouldn't have to code and test it.

I guess you're right. Perhaps we should add a simple comment about it in
README.

**Comment by gunar** [comment]
Fixed by #4.

**Pull request closed without merging**
